### ISSUE TITLE
Quick review

### ISSUE THREAD

**Issue by ben-clayton** [mattn/gxuitter#1]
Hi @mattn, I hope you don't mind me sharing a few thoughts on your usage of GXUI. I understand that this is completely unfinished and experimental (much like GXUI), but I thought I'd take a look how you were getting on.
- [You appear to be using a ScrollLayout to hold a list](https://github.com/mattn/gxuitter/blob/master/main.go#L268). A list should automatically offer scroll bars when the list content is greater than the bounds. Lists also support virtualization - i.e. the adapter will [create items](https://github.com/google/gxui/blob/master/adapter.go#L22) for only the content visible on screen. If you need a ScrollLayout in this case, I'd be interested why.
- [You are making GXUI calls on a separate go-routine](https://github.com/mattn/gxuitter/blob/master/main.go#L293). The interface to controls are not implemented to allow execution on any go-routine, they have to all come from the same UI routine. Fortunately, there is a way to cause a chunk of code to be executed on the UI go-routine:

``` go
    driver.Events() <- func() {
      /* This code will be called on the main UI go-routine */
    }
```
- The [DefaultAdapter](https://github.com/google/gxui/blob/master/default_adapter.go#L21) is great for getting something simple on screen - but you'll probably want to implement your own [Adapter](https://github.com/google/gxui/blob/master/adapter.go#L17) for fancier appearance.  I added [a sample](https://github.com/google/gxui/blob/master/samples/lists/main.go#L60) for this yesterday.

Thanks for trying out GXUI, and for your pull-requests!

**Comment by mattn** [comment]
Great Thanks! :+1:

**Comment by mattn** [comment]
I want to make vertical layout separated list and box. The box is located on bottom of window, contains textbox and button. But not works as i want. How to do it?

**Comment by ben-clayton** [comment]
What you need (and isn't implemented yet) is a way to have a LinearLayout start laying out from end to the front. I'll created [this feature request](https://github.com/google/gxui/issues/21) to get this implemented. Until then, you can still achieve something similar with the [SplitterLayout](https://github.com/google/gxui/blob/master/splitter_layout.go):

``` go
package main

import (
    "flag"

    "github.com/google/gxui"
    "github.com/google/gxui/drivers/gl"
    "github.com/google/gxui/math"
    "github.com/google/gxui/themes/dark"
)

var data = flag.String("data", "", "path to data")

func appMain(driver gxui.Driver) {
    theme := dark.CreateTheme(driver)

    adapter := gxui.CreateDefaultAdapter()
    adapter.SetData([]string{
        "zero", "one", "two", "three", "four", "five",
        "six", "seven", "eight", "nine", "ten",
        "eleven", "twelve", "thirteen", "fourteen", "fifteen",
        "sixteen", "seventeen", "eighteen", "nineteen", "twenty",
    })

    layout := theme.CreateSplitterLayout()
    layout.SetOrientation(gxui.Vertical)

    list := theme.CreateList()
    list.SetAdapter(adapter)
    list.SetOrientation(gxui.Vertical)
    layout.AddChild(list)

    text := theme.CreateTextBox()
    text.SetText("Message")

    button := theme.CreateButton()
    button.SetText("Tweet")

    row := theme.CreateLinearLayout()
    row.SetOrientation(gxui.Horizontal)
    row.AddChild(text)
    row.AddChild(button)
    layout.AddChild(row)
    layout.SetChildWeight(row, 0.1) // 10% of the full height

    window := theme.CreateWindow(800, 600, "Example")
    window.AddChild(layout)
    window.OnClose(driver.Terminate)
    window.SetPadding(math.Spacing{L: 10, T: 10, R: 10, B: 10})
    gxui.EventLoop(driver)
}

func main() {
    flag.Parse()
    gl.StartDriver(*data, appMain)
}
```

**Comment by ben-clayton** [comment]
Looking good. One more thing. You create [a closure](https://github.com/mattn/gxuitter/blob/master/main.go#L138) so you use each iterated value of tweet. A simpler solution is to assign tweet to a new local of the same name, i.e.:

``` go
for _, tweet := range tweets {
  tweet := tweet
  driver.Events() <- func() {
```

This is more efficient, and saves a couple of lines and further indentation.

**Comment by mattn** [comment]
fair enough :)

**Comment by mattn** [comment]
looks nice :ok_woman: 
https://github.com/mattn/gxuitter/commit/b4f21f7ce3fb6cf6dc3a6d60f6bdcb590283fad8

**Comment by mattn** [comment]
I'll close this issue when https://github.com/google/gxui/issues/21 is fixed.

**Comment by ben-clayton** [comment]
Added flow direction support. Let me know if that works or not for you.

**Comment by mattn** [comment]
Thanks
